FROM brandnewx/comfyui-kontext-flux:base-latest

EXPOSE 8188
EXPOSE 3000

# Set CMD to launch the comfyui-api binary. The comfyui-api binary will launch ComfyUI as a child process.
CMD ["./comfyui-api"]
